# Generated by Django 4.2.5 on 2023-10-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Star Rating', 'verbose_name_plural': 'Stars Ratings'},
        ),
    ]
